/**
 * DEMO SEED — creates (or resets) a separate workspace flagged `isDemo` with
 * ~400 days of synthetic history for UI development and review.
 *
 * It never touches non-demo workspaces. The data is generated by the same
 * deterministic model the demo-only mock connector uses, so subsequent
 * refreshes in the demo workspace continue the curves seamlessly.
 *
 *   pnpm db:seed:demo            # requires PULSE_ENABLE_DEMO=true
 */
import "dotenv/config";
import { db } from "@/server/db";
import { hashPassword } from "@/server/auth/password";
import { ingestRemoteImage } from "@/server/media";
import { accountMetricsAt, mockAccount, postMetricsAt } from "@/server/connectors/mock/model";
import { mockPostUrl } from "@/server/connectors/mock";
import { dayKey, keyToUtc } from "@/lib/dates";
import type { PlatformKey } from "@/lib/profile-url";

if (process.env.PULSE_ENABLE_DEMO !== "true") {
  console.error("Set PULSE_ENABLE_DEMO=true to seed demo data.");
  process.exit(1);
}

const DAY = 86_400_000;
const SEED_DAYS = 400;
const DEMO_EMAIL = "demo@pulse.local";
const DEMO_PASSWORD = "pulse-demo-2026";

const PORTFOLIO: { name: string; description: string; seed: number; accounts: [PlatformKey, string, string][] }[] = [
  {
    name: "Catrot",
    description: "Screen-time control app.",
    seed: 0,
    accounts: [
      ["TIKTOK", "catrotviral", "https://www.tiktok.com/@catrotviral"],
      ["TIKTOK", "catrotapp", "https://www.tiktok.com/@catrotapp"],
      ["INSTAGRAM", "catrotapp", "https://www.instagram.com/catrotapp/"],
      ["YOUTUBE", "catrot", "https://www.youtube.com/@catrot"],
    ],
  },
  {
    name: "Mealzy",
    description: "AI meal planning in 30 seconds.",
    seed: 2,
    accounts: [
      ["TIKTOK", "mealzyapp", "https://www.tiktok.com/@mealzyapp"],
      ["INSTAGRAM", "mealzyapp", "https://www.instagram.com/mealzyapp/"],
      ["TIKTOK", "mealzyrecipes", "https://www.tiktok.com/@mealzyrecipes"],
      ["YOUTUBE", "mealzy", "https://www.youtube.com/@mealzy"],
    ],
  },
  {
    name: "Picksy",
    description: "Decides where to eat, so you don't have to.",
    seed: 6,
    accounts: [
      ["TIKTOK", "picksyapp", "https://www.tiktok.com/@picksyapp"],
      ["INSTAGRAM", "picksy.app", "https://www.instagram.com/picksy.app/"],
      ["YOUTUBE", "picksy", "https://www.youtube.com/@picksy"],
    ],
  },
  {
    name: "Focus Fox",
    description: "Pomodoro timer with a fox that cheers you on.",
    seed: 11,
    accounts: [["TIKTOK", "focusfoxapp", "https://www.tiktok.com/@focusfoxapp"]],
  },
];

const big = (n: number | null) => (n === null ? null : BigInt(n));

async function chunked<T>(rows: T[], size: number, fn: (chunk: T[]) => Promise<unknown>) {
  for (let i = 0; i < rows.length; i += size) await fn(rows.slice(i, i + size));
}

async function pool<T>(items: T[], n: number, fn: (t: T) => Promise<void>) {
  const q = [...items];
  await Promise.all(Array.from({ length: n }, async () => {
    for (let x = q.shift(); x !== undefined; x = q.shift()) await fn(x);
  }));
}

async function main() {
  const started = Date.now();
  const now = Date.now();
  const tz = "UTC";

  // Workspace + demo user
  const ws = await db.workspace.upsert({
    where: { slug: "pulse-demo" },
    create: { name: "Pulse Demo", slug: "pulse-demo", isDemo: true, timezone: tz },
    update: { isDemo: true },
  });
  const user = await db.user.upsert({
    where: { email: DEMO_EMAIL },
    create: { email: DEMO_EMAIL, name: "Demo User", passwordHash: await hashPassword(DEMO_PASSWORD) },
    update: {},
  });
  const everyone = await db.user.findMany({ select: { id: true } });
  for (const u of everyone) {
    await db.membership.upsert({
      where: { userId_workspaceId: { userId: u.id, workspaceId: ws.id } },
      create: { userId: u.id, workspaceId: ws.id, role: "ADMIN" },
      update: {},
    });
  }

  // Reset demo content only.
  await db.app.deleteMany({ where: { workspaceId: ws.id } });
  await db.activityEvent.deleteMany({ where: { workspaceId: ws.id } });

  const startDay = dayKey(new Date(now - SEED_DAYS * DAY), tz);
  const start = keyToUtc(startDay).getTime();
  let created = 0;

  for (const [ai, def] of PORTFOLIO.entries()) {
    const app = await db.app.create({
      data: {
        workspaceId: ws.id,
        name: def.name,
        slug: def.name.toLowerCase().replace(/\s+/g, "-"),
        description: def.description,
        iconSeed: def.seed,
        createdAt: new Date(start - (PORTFOLIO.length - ai) * DAY),
      },
    });

    for (const [platform, handle, url] of def.accounts) {
      const m = mockAccount(platform, handle);
      const posts = m.posts.filter((p) => p.publishedAt >= start && p.publishedAt <= now);

      const avatarAssetId = await ingestRemoteImage(`mock:avatar:${m.posts[0].thumbSeed}:${m.displayName}`, "avatar");
      const account = await db.socialAccount.create({
        data: {
          workspaceId: ws.id,
          appId: app.id,
          platform,
          username: handle,
          platformAccountId: `mock-${handle}`,
          displayName: m.displayName,
          profileUrl: url,
          bio: m.bio,
          isVerified: m.verified,
          avatarAssetId,
          status: "HEALTHY",
          connectorId: "mock",
          viewsSource: platform === "YOUTUBE" ? "PROFILE" : "POSTS",
          trackingSince: new Date(start),
          lastSyncedAt: new Date(now - (5 + Math.floor(Math.random() * 50)) * 60_000),
          nextRefreshAt: new Date(now + (60 + Math.floor(Math.random() * 300)) * 60_000),
          createdAt: new Date(start),
        },
      });

      // Posts with latest metrics
      const postRows = posts.map((p) => {
        const pm = postMetricsAt(p, now)!;
        return {
          id: `${account.id}_${p.id}`.slice(0, 60),
          accountId: account.id,
          appId: app.id,
          workspaceId: ws.id,
          platform,
          platformPostId: p.id,
          url: mockPostUrl(m, p),
          thumbnailUrl: `mock:thumb:${p.thumbSeed}`,
          caption: p.caption,
          publishedAt: new Date(p.publishedAt),
          durationSec: p.durationSec,
          views: big(pm.views),
          likes: big(pm.likes),
          comments: big(pm.comments),
          shares: platform === "YOUTUBE" ? null : big(pm.shares),
          firstSeenAt: new Date(Math.max(p.publishedAt, start)),
          lastSyncedAt: new Date(now),
        };
      });
      await chunked(postRows, 2000, (c) => db.post.createMany({ data: c }));

      // Post snapshots: daily for two weeks after publish, weekly after, plus "now".
      const snaps: { postId: string; capturedAt: Date; views: bigint | null; likes: bigint | null; comments: bigint | null; shares: bigint | null }[] = [];
      for (const [i, p] of posts.entries()) {
        const postId = postRows[i].id;
        const times: number[] = [];
        for (let d = 0; p.publishedAt + d * DAY < now; d += d < 14 ? 1 : 7) times.push(p.publishedAt + d * DAY + 20 * 3600_000);
        times.push(now);
        for (const t of times) {
          if (t > now) continue;
          const pm = postMetricsAt(p, t)!;
          snaps.push({ postId, capturedAt: new Date(t), views: big(pm.views), likes: big(pm.likes), comments: big(pm.comments), shares: platform === "YOUTUBE" ? null : big(pm.shares) });
        }
      }
      await chunked(snaps, 5000, (c) => db.postMetricSnapshot.createMany({ data: c }));

      // Daily account history, computed exactly like the sync pipeline would.
      const accSnaps = [];
      const daily = [];
      for (let t = start + 20 * 3600_000; t <= now + DAY; t += DAY) {
        const at = Math.min(t, now);
        const prof = accountMetricsAt(m, at);
        let postViews = 0;
        let postLikes = 0;
        let comments = 0;
        let shares = 0;
        let count = 0;
        for (const p of posts) {
          if (p.publishedAt > at) break;
          const pm = postMetricsAt(p, at)!;
          postViews += pm.views;
          postLikes += pm.likes;
          comments += pm.comments;
          shares += pm.shares;
          count++;
        }
        const views = prof.totalViews ?? (count ? postViews : null);
        const likes = prof.totalLikes ?? (count ? postLikes : null);
        accSnaps.push({
          accountId: account.id,
          capturedAt: new Date(at),
          followers: big(prof.followers),
          following: big(prof.following),
          totalLikes: big(prof.totalLikes),
          totalViews: big(prof.totalViews),
          postCount: big(prof.postCount),
          postViews: count ? big(postViews) : null,
          postLikes: count ? big(postLikes) : null,
          views: big(views),
          viewsSource: prof.totalViews !== null ? ("PROFILE" as const) : ("POSTS" as const),
        });
        daily.push({
          accountId: account.id,
          date: keyToUtc(dayKey(new Date(at), tz)),
          followers: big(prof.followers),
          views: big(views),
          likes: big(likes),
          posts: big(prof.postCount),
          comments: count ? big(comments) : null,
          shares: count && platform !== "YOUTUBE" ? big(shares) : null,
        });
        if (at === now) {
          await db.socialAccount.update({
            where: { id: account.id },
            data: {
              followers: big(prof.followers),
              following: big(prof.following),
              totalLikes: big(likes),
              totalViews: big(views),
              postCount: big(prof.postCount),
            },
          });
          break;
        }
      }
      await chunked(accSnaps, 5000, (c) => db.accountMetricSnapshot.createMany({ data: c }));
      const uniq = new Map(daily.map((d) => [d.date.toISOString(), d]));
      await chunked([...uniq.values()], 5000, (c) => db.accountDailyMetric.createMany({ data: c }));

      // Thumbnails for everything (rendered locally, demo only).
      await pool(postRows, 8, async (p) => {
        const id = await ingestRemoteImage(p.thumbnailUrl, "thumbnail");
        if (id) await db.post.update({ where: { id: p.id }, data: { thumbnailAssetId: id } });
      });

      created += posts.length;
      console.log(`  ${def.name.padEnd(10)} ${platform.padEnd(9)} @${handle.padEnd(14)} ${String(posts.length).padStart(4)} posts · ${snaps.length} post snapshots`);
    }
  }

  // A believable recent activity stream.
  const accounts = await db.socialAccount.findMany({ where: { workspaceId: ws.id }, orderBy: { totalViews: "desc" } });
  const recentPosts = await db.post.findMany({ where: { workspaceId: ws.id }, orderBy: { publishedAt: "desc" }, take: 6 });
  const events = [
    ...recentPosts.slice(0, 4).map((p, i) => ({ type: "POST_DETECTED" as const, accountId: p.accountId, postId: p.id, at: now - (12 + i * 47) * 60_000, payload: undefined })),
    { type: "VIEWS_MILESTONE" as const, accountId: accounts[0].id, postId: null, at: now - 2 * 3600_000, payload: { viewsGained: 124_000 } },
    { type: "ACCOUNT_UPDATED" as const, accountId: accounts[3].id, postId: null, at: now - 24 * 60_000, payload: { viewsGained: 18_400 } },
    { type: "ACCOUNT_UPDATED" as const, accountId: accounts[5].id, postId: null, at: now - 5 * 3600_000, payload: { viewsGained: 9_200 } },
    { type: "VIEWS_MILESTONE" as const, accountId: accounts[1].id, postId: null, at: now - 9 * 3600_000, payload: { viewsGained: 212_000 } },
  ];
  await db.activityEvent.createMany({
    data: events.map((e) => ({ workspaceId: ws.id, type: e.type, accountId: e.accountId, postId: e.postId, payload: e.payload, createdAt: new Date(e.at) })),
  });

  console.log(`\n✓ Demo workspace ready: ${created} posts in ${((Date.now() - started) / 1000).toFixed(1)}s`);
  console.log(`  Sign in as ${DEMO_EMAIL} / ${DEMO_PASSWORD}`);
  await db.$disconnect();
  void user;
}

main().catch(async (e) => {
  console.error(e);
  await db.$disconnect();
  process.exit(1);
});
